Fix Wordservice to be an App vs Service
I tried installing the original wordservice cask and I got this error:

Error: It seems the symlink source is not there:
'/opt/homebrew-cask/Caskroom/wordservice/2.8.1/WordService/WordService.service'

After unzipping the download manually I saw that it was no longer a
"service" extension, so I made the update to the formula.